
CondaError: Run 'conda init' before 'conda activate'

/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_navigate/NavigateKitchen/2024-05-09/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_drawer/OpenDrawer/2024-05-03/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_drawer/CloseDrawer/2024-04-30/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_coffee/CoffeeSetupMug/2024-04-25/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_coffee/CoffeeServeMug/2024-05-01/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_coffee/CoffeePressButton/2024-04-25/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_microwave/TurnOnMicrowave/2024-04-25/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_microwave/TurnOffMicrowave/2024-04-25/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_doors/CloseDoubleDoor/2024-04-29/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_doors/OpenDoubleDoor/2024-04-26/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_doors/OpenSingleDoor/2024-04-24/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_doors/CloseSingleDoor/2024-04-24/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_stove/TurnOnStove/2024-05-02/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_stove/TurnOffStove/2024-05-02/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_sink/TurnOffSinkFaucet/2024-04-25/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_sink/TurnSinkSpout/2024-04-29/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_sink/TurnOnSinkFaucet/2024-04-25/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToCab/2024-04-24/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPMicrowaveToCounter/2024-04-26/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPStoveToCounter/2024-05-01/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToMicrowave/2024-04-27/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCabToCounter/2024-04-24/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPSinkToCounter/2024-04-26_2/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToSink/2024-04-25/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
/ailab/user/huanghaifeng/work/robocasa_exps/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToStove/2024-04-26/demo_gentex_im256_randcams.hdf5
Traceback (most recent call last):
  File "/ssd/home/groups/smartbot/huanghaifeng/robocasa_exps/robomimic/robomimic/scripts/dataset_states_to_obs.py", line 51, in <module>
    import robomimic.utils.tensor_utils as TensorUtils
ModuleNotFoundError: No module named 'robomimic'
